runtime: python38

instance_class: F4_1G

inbound_services:
  - warmup

automatic_scaling:
  min_idle_instances: 1
  max_instances: 1

handlers:
  - url: /slack/events
    secure: always
    script: auto

includes:
  - env_variables.yaml
